ABM_Sistemas_Plenarios/Controllers/ClientesController.cs
using Models;
using Services.ClienteServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABM_Sistemas_Plenarios.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClienteServices _iclienteServices;
        
        public ClientesController(IClienteServices iclienteServices)
        {
            _iclienteServices = iclienteServices;
           
        }
        public ActionResult Index()
        {

            Empresa empresa = (Empresa)Session["Empresa"];
            return View();
        }

        public ActionResult GetClientes()
        {
           
            var result = _iclienteServices.GetClientes().Where(x=>x.IdEmpresa ==((Empresa)Session["Empresa"]).IdEmpresa);
            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetClienteById(int id)
        {
            var result = _iclienteServices.GetClientesByID(id);
            return Json(result, JsonRequestBehavior.AllowGet);


        }
        public ActionResult InsertarCliente(Clientes clientes)
        {
            string result = "OK";
            string fecha = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
            clientes.UsuarioCreo = ((Usuario)Session["Usuario"]).Nombre + ((Usuario)Session["Usuario"]).Apellido;
            clientes.FechaRegistro = Convert.ToDateTime(fecha);
            clientes.IdEmpresa = ((Empresa)Session["Empresa"]).IdEmpresa;
            var codigoCliente = _iclienteServices.ValidarCodigo(clientes);
           
           
            if (codigoCliente != null)
            {

                if (codigoCliente.CodigoCliente == clientes.CodigoCliente)
                {
                    return Json("Codigo", JsonRequestBehavior.AllowGet);
                }
                else if (codigoCliente.RazonSocial == clientes.RazonSocial)
                {
                    return Json("Nombre", JsonRequestBehavior.AllowGet);
                }
                else  
                {
                    return Json("Documento", JsonRequestBehavior.AllowGet);
                }
            }
            else {

        
                _iclienteServices.InsertarClientes(clientes);
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            
        }

        public ActionResult EditCliente (Clientes clientes)
        {
            string result = "OK";
             
            var codigoCliente = _iclienteServices.ValidarCodigo(clientes);


            if (codigoCliente != null)
            {

                if (codigoCliente.CodigoCliente == clientes.CodigoCliente)
                {
                    return Json("Codigo", JsonRequestBehavior.AllowGet);
                }
                else if (codigoCliente.RazonSocial == clientes.RazonSocial)
                {
                    return Json("Nombre", JsonRequestBehavior.AllowGet);
                }
                else  
                {
                    return Json("Documento", JsonRequestBehavior.AllowGet);
                }
            }

            else
            {
                
                 clientes.UsuarioEdito = ((Usuario)Session["Usuario"]).Nombre + ((Usuario)Session["Usuario"]).Apellido;
                 clientes.IdEmpresa = ((Empresa)Session["Empresa"]).IdEmpresa;
                _iclienteServices.Edit(clientes);
                 return Json(result, JsonRequestBehavior.AllowGet);
            }
            
            
        }
        public ActionResult DeleteCliente(int id)
        {

            string result = "OK";
            _iclienteServices.Delete(id);
            return Json(result, JsonRequestBehavior.AllowGet);
                
        }

    }
}

ABM_Sistemas_Plenarios/Controllers/EmpresasController.cs
using ABM_Sistemas_Plenarios.Models;
using Models;
using Services.EmpresasServices;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABM_Sistemas_Plenarios.Controllers
{

    
    public class EmpresasController : Controller
    {
        string result = "OK";
        
      
        private readonly IEmpresaServices _IempresasServices;

        public EmpresasController(IEmpresaServices IempresasServices)

        {
            _IempresasServices = IempresasServices;
        }
        public ActionResult Index()
        {
            return View();
        }

       
        public ActionResult Inicio(int IdEmpresa)
        {
            try
            {
                var result = _IempresasServices.GetById(IdEmpresa);
                Session["Empresa"] = result;

                return Json("OK", JsonRequestBehavior.AllowGet);
            }
            catch(Exception e)
            {
                return Json("OK", JsonRequestBehavior.AllowGet);
            }
           

        }
        public ActionResult Get()
        {
            var result = _IempresasServices.Get();
            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetById(int id=0)
        {

            if(id == 0)
            {
                Empresa empresa = (Empresa)Session["Empresa"];
                id = empresa.IdEmpresa;
            }
            var result = _IempresasServices.GetById(id);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Insert(Empresa empresa)
        {
            Usuario osuario = (Usuario)Session["Usuario"];
            string fecha = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
            UploadImages file = (UploadImages)Session["Upload"];
            empresa.Logo = file.ImageFile.FileName;
            empresa.FechaRegistro = Convert.ToDateTime(fecha);
            empresa.UsuarioCreo = osuario.Nombre;
            empresa.Activo = 1;
            _IempresasServices.Insert(empresa);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult InsertarFirst(Empresa empresa)
        {
            Usuario osuario = (Usuario)Session["Usuario"];
            string fecha = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
            UploadImages file = (UploadImages)Session["Upload"];
            empresa.Logo = file.ImageFile.FileName;
            empresa.FechaRegistro = Convert.ToDateTime(fecha);
            empresa.UsuarioCreo = osuario.Nombre;


            int id =_IempresasServices.Insert(empresa);
            return Json(id, JsonRequestBehavior.AllowGet);

        
        }
        public ActionResult Edit(Empresa empresa)
        {
            _IempresasServices.Edit(empresa);
            return Json(result, JsonRequestBehavior.AllowGet);

        }

        public ActionResult delete(int id)
        {
            _IempresasServices.detele(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult Upload( UploadImages file)
        {
            if (file != null)
            {
                try
                {
                    string Filename = Path.GetFileNameWithoutExtension(file.ImageFile.FileName);
                    string extension = Path.GetExtension(file.ImageFile.FileName);

                    if (extension == ".jpg" || extension == ".PNG" || extension==".png")

                    {
                        //Filename = Filename + DateTime.Now.ToString("ddmmyyyyy") + extension;
                        //file.path = "/ImagenesEmpresa/" + Filename + extension;
                        file.ImageFile.SaveAs(Server.MapPath("/ImagenesEmpresa/" + Filename + extension));


                        Session["Upload"] = file;


                        return Json("OK", JsonRequestBehavior.AllowGet);
                    }
                    else return Json("Error", JsonRequestBehavior.AllowGet);
                }
                catch (Exception e)
                {
                    string r = "No se pudo cargar el archivo" + e;
                    return Json(r, JsonRequestBehavior.AllowGet);
                }
            }
            else return  Json("null", JsonRequestBehavior.AllowGet);

        }
    }
}

ABM_Sistemas_Plenarios/Controllers/MonedaController.cs
using Models;
using Services.MonedaServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABM_Sistemas_Plenarios.Controllers
{
    public class MonedaController : Controller
    {
        private readonly IMonedaServices _ImonedaServices;
        public MonedaController(IMonedaServices ImonedaServices)
        {
            _ImonedaServices = ImonedaServices;
        }
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Get()
        {
            var result = _ImonedaServices.Get();
            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetById(int id)
        {
            var result = _ImonedaServices.GetById(id);
           return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Edit(Moneda moneda)
        {
            var Fecha = DateTime.Now.ToString("dd/MM/yyyyy hh:mm:ss");
            moneda.FechaModificacion = Convert.ToDateTime(Fecha);
            moneda.UsuarioModifico = ((Usuario)Session["Usuario"]).Nombre + ((Usuario)Session["Usuario"]).Apellido;
            _ImonedaServices.Edit(moneda);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
        public ActionResult Insert(Moneda moneda)
        {
            var Fecha = DateTime.Now.ToString("dd/MM/yyyyy hh:mm:ss");
            moneda.UsuarioRegistro = ((Usuario)Session["Usuario"]).Nombre + ((Usuario)Session["Usuario"]).Apellido;
            moneda.FechaRegistro = Convert.ToDateTime(Fecha);
            moneda.IdEmpresa = ((Empresa)Session["Empresa"]).IdEmpresa;
            _ImonedaServices.Insert(moneda);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            _ImonedaServices.Delelte(id);
            return Json("OK", JsonRequestBehavior.AllowGet);

        }
    }
}

ABM_Sistemas_Plenarios/Controllers/PerfilesController.cs
using Models;
using Services.PerfilesServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ABM_Sistemas_Plenarios.Controllers
{
    public class PerfilesController : Controller
    {
        private readonly IPerfilesServices _IPerfilesServices;
        public PerfilesController(IPerfilesServices IPerfilesServices)
        {
            _IPerfilesServices = IPerfilesServices;
        }
        public ActionResult Index()
        {
           
            return View();
        }

        public ActionResult Get()
        {
            var result = _IPerfilesServices.Get();
            return Json(new { data = result }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetById(int id)
        {
            var result = _IPerfilesServices.GetById(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit (UsuarioRol usuarioRol)
        {
            _IPerfilesServices.Edit(usuarioRol);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Insert(UsuarioRol usuarioRol)
        {
             _IPerfilesServices.Insert(usuarioRol);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id )
        {
            _IPerfilesServices.Delete(id);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetPerfiles()
        {
            var result = _IPerfilesServices.Get();
            return Json(result , JsonRequestBehavior.AllowGet);
        }


    }
}

ABM_Sistemas_Plenarios/Views/Shared/Layout_Login.cshtml
@{
    ViewBag.Title = "Layout_Login";
}



@RenderBody()
@RenderSection("scripts", required: false)

ABM_Sistemas_Plenarios/Views/Shared/_Footer.cshtml
<div class="footer">
    <div class="pull-right">
        
    </div>
    <div>
        <strong>Create By Argenis Riera</strong> 
    </div>
</div>

ABM_Sistemas_Plenarios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable =no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Sistema| @ViewBag.Title</title>

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}


    <link href="~/Content/dist/css/skins/_all-skins.min.css" rel="stylesheet" />
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    @*<link href="~/Content/Site.css" rel="stylesheet" />*@
    @*<link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link href="~/Content/dist/css/AdminLTE.css" rel="stylesheet" />
    <!-- Primary Inspinia style -->
    <link href="~/Content/dist/css/AdminLTE.min.css" rel="stylesheet" />
   
    <link href="~/Content/plugins/toastr/toastr.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/font-awesome/css")

    <style>

        /*  .Caja {
              position: absolute;
              top: 60%;
              left: 50%;
              transform: translate(-50%,-50%);
              width: 1720px;
              height: 1000px;
              padding: 80px 40px;

          }
        */


    </style>

</head>
<body>

    <div class="contenedor" style="overflow-x:auto;">

        <!-- Skin configuration box -->
        <!-- @Html.Partial("_SkinConfig") -->
        <!-- Wrapper-->
        <!-- PageClass give you ability to specify custom style for specific view based on action -->
        <div id="wrapper">

            <!-- Navigation -->
            @Html.Partial("_Navigation")

            <!-- Page wraper -->
            <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

                <!-- Top Navbar -->
                @Html.Partial("_TopNavbar")

                <!-- Main view  -->
                @RenderBody()

                <!-- Footer -->
                @Html.Partial("_Footer")

            </div>

        </div>
    </div>
    <!-- End page wrapper-->
    <!-- Right Sidebar -->
    @*@Html.Partial("_RightSidebar")*@




    <!-- End wrapper-->
    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")
    <script src="~/Scripts/plugins/toastr/toastr.min.js"></script>
    <script src="~/Content/dist/js/demo.js"></script>
    <!-- Skin config script - only for demo purpose-->
    @*@Scripts.Render("~/bundles/skinConfig")*@
    @*<script src="~/Content/dist/js/app.min.js"></script>*@
    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)


</body>

</html>

ABM_Sistemas_Plenarios/Views/Shared/_Layout_2.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>INSPINIA | @ViewBag.Title</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
     
    <!-- Add jQuery Style direct - used for jQGrid plugin -->
    <link href="@Url.Content("~/Scripts/plugins/jquery-ui/jquery-ui.min.css")" rel="stylesheet" type="text/css" />

    <!-- Primary Inspinia style -->     
    @Styles.Render("~/font-awesome/css")                                                
    @Styles.Render("~/Content/css")
</head>
<body class="top-navigation">

    <!-- Skin configuration box -->
    @Html.Partial("_SkinConfig")

    <!-- Wrapper-->
    <!-- PageClass give you ability to specify custom style for specific view based on action -->
    <div id="wrapper">

        <!-- Page wraper -->
        <div id="page-wrapper" class="gray-bg @ViewBag.SpecialClass">

            <!-- Top Navbar -->
            @Html.Partial("_TopNavbar2")

            <!-- Main view  -->
            @RenderBody()

            <!-- Footer -->
            @Html.Partial("_Footer")

        </div>
        <!-- End page wrapper-->

    </div>
    <!-- End wrapper-->

    <!-- Section for main scripts render -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/plugins/slimScroll")
    @Scripts.Render("~/bundles/inspinia")

    <!-- Skin config script - only for demo purpose-->
    @Scripts.Render("~/bundles/skinConfig")

    <!-- Handler for local scripts -->
    @RenderSection("scripts", required: false)
</body>
</html>

ABM_Sistemas_Plenarios/Views/Shared/_Navigation.cshtml
@using ABM_Sistemas_Plenarios.Filters;
@using Models;
@using ConexionBD;

@{

    var oUsuario = (Usuario)HttpContext.Current.Session["usuario"];
    

    
    


}


<style>



    .avatar {
        position: absolute;
        width: 100px;
        height: 100px;
        border-radius: 50%;
        border: 4px solid #FFF;
        overflow: hidden;
        top: calc(-60px/2);
        left: calc(40% - 40px);
    }
</style>
@if (oUsuario != null)
{
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">

                    <div class="dropdown profile-element">
                       


                        <span>
                          
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear">
                                <img alt="image" class="avatar" src="~/Content/Images/usuarios/default.png" />
                                <span class="block m-t-xs">
                                    @if (oUsuario != null)
                                    {
                                        <strong class="font-bold">@oUsuario.Nombre    @oUsuario.Apellido</strong>

                                    }
                                    else
                                    {
                                        <strong class="font-bold"></strong>
                                    }
                                    @*<span class="block m-t-xs">
                @if (oUsuario.IdRol == 1)
                {
                    <strong class="font-bold">Administrador</strong>
                }
                else
                {
                    <strong class="font-bold"></strong>
                }
            </span>*@
                                </span>

                            </span>
</a>
                        @*<a data-toggle="dropdown" class="dropdown-toggle" href="#">

            <span class="clear">
                <span class="block m-t-xs">






                    @if (oUsuario != null)
                    {
                        <strong class="">@oUsuario.Nombre @oUsuario.Apellido</strong>
                    }
                    else
                    {
                        <strong class="font-bold"></strong>
                    }
                </span>


            </span>


        </a>*@

                    </div>

                </li>

              
                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Ventas</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        @*<li class="">
                    <a href="@Url.Action("Index","Personas")"><i></i> Personas</a>
                </li>*@

                        <li class="">
                            <a href="@Url.Action("Index", "Clientes")"><i></i> Clientes</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "Clientes")"><i></i> Factura Venta</a>
                        </li>

                    </ul>
                </li>
                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Almacenes</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        @*<li class="">
            <a href="@Url.Action("Index","Personas")"><i></i> Personas</a>
        </li>*@

                        <li class="clientes">
                            <a href="@Url.Action("Index", "Clientes")"><i></i> Lista de Almacenes</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "Productos")"><i></i>Productos</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "EstadoProductos")"><i></i> Estado Productos</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "EstadoDespachos")"><i></i>Estado Despachos</a>
                        </li>

                        

                    </ul>
                </li>


                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Compras</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        <li class="">
                            <a href="@Url.Action("Index", "Proveedores")"><i></i> Proveedores</a>
                            <a href="@Url.Action("Index", "Requerimiento")"><i></i> Requerimiento</a>
                            <a href="@Url.Action("Index", "Proveedores")"><i></i> Orden de Compra</a>
                            <a href="@Url.Action("Index", "Proveedores")"><i></i> Factura de Compra</a>
                        </li>



                       
                    </ul>
                </li>

               
                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Configuración</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        @*<li class="">
            <a href="@Url.Action("Index","Personas")"><i></i> Personas</a>
        </li>*@


                        <li class="">
                            <a href="@Url.Action("Index", "UnidadMedida")"><i></i>Unidad Medida</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "Moneda")"><i></i>Moneda</a>
                        </li>
                        @if (oUsuario.Flag == 1)
                        {
                            <li class="">
                                <a href="@Url.Action("Index", "Usuarios")"><i></i>Config Usuarios</a>
                                <a href="@Url.Action("Index","Empresas")"><i></i>Config. Empresa</a>
                                <a href="@Url.Action("Index","Perfiles")"><i></i>Perfiles</a>
                            </li>
                        }

                    </ul>
                </li>
            </ul>
        </div>
    </nav>

}

@*@section Scripts {

    <script src="~/Scripts/plugins/metisMenu/metisMenu.min.js"></script>
    <script>
        $(function () {
            $('#side-menu').metisMenu({ toggle: false });
        });
    </script>
}*@

ABM_Sistemas_Plenarios/Views/Shared/_Navigation2.cshtml
@using ABM_Sistemas_Plenarios.Filters;
@using Models;
@{

    var oUsuario = (Usuario)HttpContext.Current.Session["usuario"];



}


<style>



    .avatar {
        position: absolute;
        width: 100px;
        height: 100px;
        border-radius: 50%;
        overflow: hidden;
        top: calc(-60px/2);
        left: calc(40% - 40px);
    }
</style>
@if (oUsuario != null)
{
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">

                    <div class="dropdown profile-element">



                        <span>
                            <img alt="image" class="avatar" src="~/Content/Images/usuarios/default.png" />
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear">
                                <span class="block m-t-xs">
                                    @if (oUsuario != null)
                                    {
                                        <strong class="font-bold">@oUsuario.Nombre     @oUsuario.Apellido</strong>
                                    }
                                    else
                                    {
                                        <strong class="font-bold"></strong>
                                    }
                                </span>
                            </span>
                        </a>
                        

                    </div>

                </li>


                <!--<li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Ventas</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">-->
                        @*<li class="">
                                <a href="@Url.Action("Index","Personas")"><i></i> Personas</a>
                            </li>*@

                        <!--<li class="">
                            <a href="@Url.Action("Index", "Clientes")"><i></i> Clientes</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "Clientes")"><i></i> Factura Venta</a>
                        </li>

                    </ul>
                </li>
                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Almacenes</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">-->
                        @*<li class="">
                                <a href="@Url.Action("Index","Personas")"><i></i> Personas</a>
                            </li>*@

                        <!--<li class="clientes">
                            <a href="@Url.Action("Index", "Clientes")"><i></i> Lista de Almacenes</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "Productos")"><i></i>Productos</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "EstadoProductos")"><i></i> Estado Productos</a>
                        </li>
                        <li class="">
                            <a href="@Url.Action("Index", "EstadoDespachos")"><i></i>Estado Despachos</a>
                        </li>



                    </ul>
                </li>


                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Compras</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        <li class="">
                            <a href="@Url.Action("Index","Proveedores")"><i></i> Proveedores</a>
                            <a href="@Url.Action("Index","Proveedores")"><i></i> Requerimiento</a>
                            <a href="@Url.Action("Index","Proveedores")"><i></i> Orden de Compra</a>
                            <a href="@Url.Action("Index","Proveedores")"><i></i> Factura de Compra</a>
                        </li>




                    </ul>
                </li>-->

                <li class="">
                    <a href="#">
                        <i class=""></i>
                        <span class="nav-label"></span> <span>Configuración</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-right pull-right"></i>
                        </span>
                    </a>
                    <ul class="nav nav-second-level collapse">
                        @*<li class="">
                                <a href="@Url.Action("Index","Personas")"><i></i> Personas</a>
                            </li>*@



                        @if (oUsuario.Flag == 1)
                        {
                            <li class="">
                                <a href="@Url.Action("Index", "Usuarios")"><i></i>Config Usuarios</a>
                                <a href="@Url.Action("Index","Empresas")"><i></i>Config. Empresa</a>
                            </li>
                        }

                    </ul>
                </li>
            </ul>
        </div>
    </nav>

}

@*@section Scripts {

        <script src="~/Scripts/plugins/metisMenu/metisMenu.min.js"></script>
        <script>
            $(function () {
                $('#side-menu').metisMenu({ toggle: false });
            });
        </script>
    }*@